Maps:
  MissileWars:
    Name: Missile Wars
    Author: SethBling and Cubehamster
    DownloadLink: https://dl.dropbox.com/s/f32uypmyfwfpv3x/MissileWars.zip
    FileName: MissileWars.zip
    FolderName: MissileWars
